version: "2.0"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/docker/proxy/html:/usr/share/nginx/html
      - ./vhosts:/etc/nginx/vhost.d
      - /srv/docker/letsencrypt/certs:/etc/nginx/certs:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.0
    container_name: letsencrypt
    restart: always
    depends_on:
      - proxy
    environment:
      - DEFAULT_EMAIL=guillaume@oups.net
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/docker/letsencrypt/certs:/etc/nginx/certs
      - /srv/docker/letsencrypt/acme.sh:/etc/acme.sh

  webinno:
    image: 'docker.pkg.github.com/univ-smb-m1-isc-2020/webinno/webinno:latest'
    container_name: webinno
    restart: always
    environment:
      - VIRTUAL_HOST=webinno.oups.net
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=webinno.oups.net